# Generated by Django 4.2 on 2023-05-06 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web1', '0002_diem_diemanh_diem_diemcongnghe_diem_diemdia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='personal_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=40)),
                ('lastname', models.CharField(max_length=40)),
                ('lop', models.CharField(max_length=40)),
                ('truong', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vieccanlam1', models.CharField(max_length=40)),
                ('vieccanlam2', models.CharField(max_length=40)),
                ('vieccanlam3', models.CharField(max_length=40)),
                ('vieccanlam4', models.CharField(max_length=40)),
            ],
        ),
    ]
