# Generated by Django 4.2 on 2023-05-06 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web1', '0003_personal_info_todo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='personal_info',
            new_name='personalin_fo',
        ),
    ]
