# Generated by Django 4.2 on 2023-05-06 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web1', '0004_rename_personal_info_personalin_fo'),
    ]

    operations = [
        migrations.CreateModel(
            name='my_goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shorttermgoal1', models.CharField(max_length=40)),
                ('shorttermgoal2', models.CharField(max_length=40)),
                ('shorttermgoal3', models.CharField(max_length=40)),
                ('shorttermgoal4', models.CharField(max_length=40)),
                ('shorttermgoal5', models.CharField(max_length=40)),
                ('longtermgoal1', models.CharField(max_length=40)),
                ('longtermgoal2', models.CharField(max_length=40)),
                ('longtermgoal3', models.CharField(max_length=40)),
                ('longtermgoal4', models.CharField(max_length=40)),
                ('longtermgoal5', models.CharField(max_length=40)),
            ],
        ),
    ]
