# Generated by Django 4.2 on 2023-05-06 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web1', '0006_my_goal_date1_personalin_fo_gioitinh_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='my_goal',
            name='date2',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='my_goal',
            name='date3',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='my_goal',
            name='date4',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='my_goal',
            name='date5',
            field=models.DateTimeField(null=True),
        ),
    ]
