# Generated by Django 4.2 on 2023-05-05 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diem',
            name='diemanh',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='diem',
            name='diemcongnghe',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='diem',
            name='diemdia',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='diem',
            name='diemgdcd',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='diem',
            name='diemly',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='diem',
            name='diemsinh',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='diem',
            name='diemsu',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='diem',
            name='diemhoa',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='diem',
            name='diemtoan',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='diem',
            name='diemvan',
            field=models.FloatField(default=0),
        ),
    ]
